---
image: alpine:latest

variables:
  GITLAB_HOST: gitlab.com
  CI_REGISTRY: "index.docker.io"
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY/$CI_PROJECT_PATH
  CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
  CI_CONTAINER_NAME: ci_job_build_${CI_JOB_ID}
  TILLER_NAMESPACE: "kube-system"

stages:
  - test
  - staging
  - production

test:
  stage: test
  script:
    - exit 0
  only:
    - triggers
    - branches

staging:
  stage: staging
  variables:
    KUBE_NAMESPACE: staging
    host: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    name: $CI_ENVIRONMENT_SLUG
  environment:
    name: staging
    url: http://staging

  before_script:
    - apk add -U openssl curl tar gzip bash ca-certificates git
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
    - apk add glibc-2.23-r3.apk
    - curl https://storage.googleapis.com/pub/gsutil.tar.gz | tar -xz -C $HOME
    - export PATH=${PATH}:$HOME/gsutil
    - curl https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz | tar zx
    - mv linux-amd64/helm /usr/bin/
    - helm version --client
    - curl  -o /usr/bin/sync-repo.sh https://raw.githubusercontent.com/kubernetes/helm/master/scripts/sync-repo.sh
    - chmod a+x /usr/bin/sync-repo.sh
    - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x /usr/bin/kubectl
    - kubectl version --client
    - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
    - echo "Checking Tiller..."
    - helm init --upgrade
    - kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
    - if ! helm version --debug; then
        echo "Failed to init Tiller."
        exit 1
      fi
  script:
    - export track="${1-stable}"
    - if [[ "$track" != "stable" ]]; then
        name="$name-$track"
      fi
    - echo "Clone deploy repository..."
    - git clone http://gitlab-gitlab/$CI_PROJECT_NAMESPACE/reddit-deploy.git
    - echo "Download helm dependencies..."
    - helm dep update reddit-deploy/reddit
    - echo "Deploy helm release $name to $KUBE_NAMESPACE"
    - echo "Upgrading existing release..."
    - echo "helm upgrade --install --wait --set ui.ingress.host="$host" --set $CI_PROJECT_NAME.image.tag="$CI_APPLICATION_TAG" --namespace="$KUBE_NAMESPACE" --version="$CI_PIPELINE_ID-$CI_JOB_ID" "$name" reddit-deploy/reddit/"
    - helm upgrade \
        --install \
        --force \
        --wait \
        --set ui.ingress.host="$host" \
        --set $CI_PROJECT_NAME.image.tag="$CI_APPLICATION_TAG" \
        --namespace="$KUBE_NAMESPACE" \
        --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
        "$name" \
        reddit
  only:
    refs:
      - master
    kubernetes: active
  except:
    - triggers

production:
  stage: production

  variables:
    host: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    name: $CI_ENVIRONMENT_SLUG
  environment:
    name: production
    url: http://production
  script:
  - apk add -U openssl curl tar gzip bash ca-certificates git
  - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
  - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
  - apk add glibc-2.23-r3.apk
  - rm glibc-2.23-r3.apk
  - curl https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz | tar zx
  - mv linux-amd64/helm /usr/bin/
  - helm version --client
  - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x /usr/bin/kubectl
  - kubectl version --client
  - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
  - echo "Checking Tiller..."
  - helm init --client-only --skip-refresh
  - helm repo rm stable
  - helm repo add stable https://charts.helm.sh/stable
  - kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
  - if ! helm version --debug; then
      echo "Failed to init Tiller."
      return 1
    fi
  - echo ""
  - helm upgrade  --install
    --wait
    --force
    --set ui.ingress.host="$host"
    --set $CI_PROJECT_NAME.image.tag="$CI_APPLICATION_TAG"
    --namespace="$KUBE_NAMESPACE"
    --version="$CI_PIPELINE_ID-$CI_JOB_ID"
    "$name"
    reddit

  except:
    - pushes

  only:
    refs:
      - master
    kubernetes: active
